# Generated by Django 5.1.3 on 2025-03-24 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0552973d-e01e-4f0b-b52b-84294a1e93db'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
