# Generated by Django 5.1.3 on 2025-03-24 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_id_alter_user_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('99c4dc32-c5ff-4faa-9857-033ecee85417'), primary_key=True, serialize=False, unique=True),
        ),
    ]
