# Generated by Django 5.1.3 on 2025-03-24 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2e9f66d4-fd83-4713-a31f-fab5e97be5eb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
