# Generated by Django 5.1.3 on 2025-03-25 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('bfbf5c84-8651-427c-ae7f-452cecf69e04'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
