# Generated by Django 5.1.3 on 2025-04-01 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('96e7706e-d660-4204-8d55-5089c721a4d9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
