# Generated by Django 5.1.3 on 2025-03-18 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_item_alter_review_review_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.UUID('5c3d30e1-46cb-4821-9029-8f5f1757e4b8'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('8b5fc72d-4060-415f-ac7b-8f848e178e71'), primary_key=True, serialize=False, unique=True),
        ),
    ]
