# Generated by Django 5.1.3 on 2025-03-25 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_item_item_id_alter_review_review_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.UUID('32ba7489-d852-4349-8138-d688f5ea6a67'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('eed78b69-3e05-4b2c-b3be-d53f3fe788f2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
