# Generated by Django 5.1.3 on 2025-03-25 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_item_item_id_alter_review_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_from',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.UUID('afb1425c-cf37-4236-a8da-fa71fc190091'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('66fbdcde-2cc6-4e5f-99ec-8f389730fff3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
